"use client";

import { useEffect, useState } from "react";
import { actorHeaders } from "@/lib/portal-client";
import { usePortalActor } from "@/lib/portal-actor";
import { can } from "@/lib/portal-state";

type Job = { id: number; source: string; status: string; listingsFound: number | null; listingsNew: number | null; createdAt: string | null; searchParams: { location?: string } | null };

export default function ScraperPage() {
  const actor = usePortalActor();
  const canEdit = can(actor?.role ?? "Viewer", "record");
  const [jobs, setJobs] = useState<Job[]>([]);
  const [source, setSource] = useState("property24");
  const [location, setLocation] = useState("Midrand");
  const [message, setMessage] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/scrape/jobs"); if (response.ok) setJobs(await response.json()); }
  useEffect(() => { const initial = window.setTimeout(load, 0); const timer = window.setInterval(load, 5000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, []);
  async function trigger(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/scrape/jobs", { method: "POST", headers: actorHeaders(), body: JSON.stringify({ source, location, radiusKm: 20, minSizeSqm: 300, maxPrice: 5000000 }) }); const body = await response.json(); setMessage(response.ok ? `Job #${body.id} queued.` : body.error ?? "Could not queue job"); if (response.ok) load(); }
  async function run(id: number) { const response = await fetch(`/api/scrape/jobs/${id}/run`, { method: "POST", headers: actorHeaders() }); const body = await response.json(); setMessage(response.ok ? `Job #${id} finished with ${body.listings?.length ?? 0} listings.` : body.error ?? "Could not run job"); load(); }
  if (!canEdit) return <div className="portal-page"><div className="portal-page-head"><div><p className="eyebrow">Admin · Lead ingestion</p><h1 className="page-title">Scraper jobs</h1><p className="page-subtitle">Read-only job history for the listing ingestion network.</p></div></div><section className="card card-pad"><div className="split"><div><span className="card-kicker">Job history</span><h2 className="card-title" style={{ marginTop: 6 }}>Recent ingestion runs</h2></div><span className="tag">Read-only</span></div>{jobs.map((job) => <div className="list-row" key={job.id}><span><strong>#{job.id} · {job.source}</strong><small>{job.searchParams?.location ?? "Gauteng"} · {job.createdAt ? new Date(job.createdAt).toLocaleString("en-ZA") : "Queued"}</small></span><span className={`tag ${job.status === "complete" ? "tag-green" : job.status === "failed" ? "tag-red" : "tag-amber"}`}>{job.status}</span></div>)}{jobs.length === 0 && <p className="muted" style={{ marginTop: 16, fontSize: 12 }}>No scraper jobs yet.</p>}</section></div>;
  return <div className="portal-page"><div className="portal-page-head"><div><p className="eyebrow">Admin · Lead ingestion</p><h1 className="page-title">Scraper jobs</h1><p className="page-subtitle">Queue source searches, monitor ingestion, and review what enters the Scout pipeline.</p></div></div>{message && <div className="card status-banner-success" style={{ padding: "12px 16px", marginBottom: 16, fontSize: 12, fontWeight: 800 }}>{message}</div>}<section className="card card-pad" style={{ marginBottom: 18 }}><span className="card-kicker">Queue a search</span><h2 className="card-title" style={{ marginTop: 6 }}>Find new Gauteng listings</h2><form className="form-grid" style={{ marginTop: 16 }} onSubmit={trigger}><label className="field-label">Source<select className="field" value={source} onChange={(event) => setSource(event.target.value)}>{["property24", "private_property", "propdata", "gumtree", "immo_africa", "entegral"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field-label">Location<input className="field" value={location} onChange={(event) => setLocation(event.target.value)} required /></label><button className="button button-primary" type="submit">Queue scraper job</button></form></section><section className="card card-pad"><div className="split"><div><span className="card-kicker">Job history</span><h2 className="card-title" style={{ marginTop: 6 }}>Recent ingestion runs</h2></div><span className="tag tag-blue">Polling every 5 seconds</span></div>{jobs.map((job) => <div className="list-row" key={job.id}><span><strong>#{job.id} · {job.source}</strong><small>{job.searchParams?.location ?? "Gauteng"} · {job.createdAt ? new Date(job.createdAt).toLocaleString("en-ZA") : "Queued"}</small></span><span className="split"><span className={`tag ${job.status === "complete" ? "tag-green" : job.status === "failed" ? "tag-red" : "tag-amber"}`}>{job.status}</span><small className="muted">{job.listingsNew ?? 0} new</small>{job.status === "queued" && <button className="button button-secondary" style={{ minHeight: 30, padding: "0 9px" }} onClick={() => run(job.id)}>Run now</button>}</span></div>)}{jobs.length === 0 && <p className="muted" style={{ marginTop: 16, fontSize: 12 }}>No scraper jobs yet.</p>}</section></div>;
}
