import { db, zoningSchemeRules } from "@fgp/database";

// Curated zoning scheme rules transcribed from municipal town-planning schemes.
// Covers Johannesburg, Tshwane and Ekurhuleni — Residential 1-4 plus Business 1.
// Rules change rarely, so they live in the DB rather than in code (see CLAUDE.md).
const rules = [
  // ---- Johannesburg (Town Planning Scheme 2018) ----
  { municipality: "johannesburg", zoneCode: "RES1", zoneLabel: "Residential 1", maxUnitsPerErf: 1, coveragePct: "40", far: "0.5", maxStoreys: 2, buildingLineFrontM: "4.5", buildingLineSideM: "1.5", buildingLineRearM: "3", permittedUses: ["single_dwelling"], rezoningPossibleTo: ["RES2", "RES3"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist"], schemeYear: 2018 },
  { municipality: "johannesburg", zoneCode: "RES2", zoneLabel: "Residential 2", maxUnitsPerErf: 2, coveragePct: "50", far: "0.75", maxStoreys: 2, buildingLineFrontM: "4.5", buildingLineSideM: "1.5", buildingLineRearM: "3", permittedUses: ["dwelling_units", "second_dwelling"], rezoningPossibleTo: ["RES3", "RES4"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist"], schemeYear: 2018 },
  { municipality: "johannesburg", zoneCode: "RES3", zoneLabel: "Residential 3", maxUnitsPerHa: 80, coveragePct: "60", far: "1.5", maxStoreys: 3, buildingLineFrontM: "3", buildingLineSideM: "1.5", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "low", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter"], schemeYear: 2018 },
  { municipality: "johannesburg", zoneCode: "RES4", zoneLabel: "Residential 4", maxUnitsPerHa: 120, coveragePct: "70", far: "2.5", maxStoreys: 4, buildingLineFrontM: "2", buildingLineSideM: "1", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: [], rezoningDifficulty: "low", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter"], schemeYear: 2018 },
  { municipality: "johannesburg", zoneCode: "COM1", zoneLabel: "Business 1", maxUnitsPerHa: 150, coveragePct: "80", far: "3.0", maxStoreys: 6, buildingLineFrontM: "0", buildingLineSideM: "0", buildingLineRearM: "3", permittedUses: ["retail", "offices", "mixed_use"], consentUses: ["flats", "residential_above_ground"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter"], schemeYear: 2018 },

  // ---- Tshwane (Town Planning Scheme 2008, rev 2016) ----
  { municipality: "tshwane", zoneCode: "RES1", zoneLabel: "Residential 1", maxUnitsPerErf: 1, coveragePct: "40", far: "0.4", maxStoreys: 2, buildingLineFrontM: "4.5", buildingLineSideM: "1.5", buildingLineRearM: "3", permittedUses: ["single_dwelling"], rezoningPossibleTo: ["RES2", "RES3"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist", "dolomite_declaration"], schemeYear: 2016 },
  { municipality: "tshwane", zoneCode: "RES2", zoneLabel: "Residential 2", maxUnitsPerErf: 2, coveragePct: "50", far: "0.6", maxStoreys: 2, buildingLineFrontM: "4.5", buildingLineSideM: "1.5", buildingLineRearM: "3", permittedUses: ["dwelling_units"], rezoningPossibleTo: ["RES3", "RES4"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist", "dolomite_declaration"], schemeYear: 2016 },
  { municipality: "tshwane", zoneCode: "RES3", zoneLabel: "Residential 3", maxUnitsPerHa: 60, coveragePct: "55", far: "1.2", maxStoreys: 3, buildingLineFrontM: "3", buildingLineSideM: "1.5", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "low", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter", "dolomite_declaration"], schemeYear: 2016 },
  { municipality: "tshwane", zoneCode: "RES4", zoneLabel: "Residential 4", maxUnitsPerHa: 100, coveragePct: "65", far: "2.0", maxStoreys: 4, buildingLineFrontM: "2", buildingLineSideM: "1", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: [], rezoningDifficulty: "low", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter", "dolomite_declaration"], schemeYear: 2016 },
  { municipality: "tshwane", zoneCode: "COM1", zoneLabel: "Business 1", maxUnitsPerHa: 140, coveragePct: "75", far: "2.5", maxStoreys: 5, buildingLineFrontM: "0", buildingLineSideM: "0", buildingLineRearM: "3", permittedUses: ["retail", "offices", "mixed_use"], consentUses: ["flats"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "medium", formsRequired: ["zoning_certificate", "building_plan_checklist", "motivation_letter", "dolomite_declaration"], schemeYear: 2016 },

  // ---- Ekurhuleni (Town Planning Scheme 2014) ----
  { municipality: "ekurhuleni", zoneCode: "RES1", zoneLabel: "Residential 1", maxUnitsPerErf: 1, coveragePct: "60", far: "0.6", maxStoreys: 2, buildingLineFrontM: "5", buildingLineSideM: "2", buildingLineRearM: "3", permittedUses: ["single_dwelling"], rezoningPossibleTo: ["RES2", "RES3"], rezoningDifficulty: "medium", formsRequired: ["splum_form_ekurhuleni", "building_plan_checklist"], schemeYear: 2014 },
  { municipality: "ekurhuleni", zoneCode: "RES2", zoneLabel: "Residential 2", maxUnitsPerErf: 3, coveragePct: "60", far: "0.8", maxStoreys: 2, buildingLineFrontM: "5", buildingLineSideM: "2", buildingLineRearM: "3", permittedUses: ["dwelling_units", "second_dwelling"], rezoningPossibleTo: ["RES3", "RES4"], rezoningDifficulty: "medium", formsRequired: ["splum_form_ekurhuleni", "building_plan_checklist"], schemeYear: 2014 },
  { municipality: "ekurhuleni", zoneCode: "RES3", zoneLabel: "Residential 3", maxUnitsPerHa: 70, coveragePct: "60", far: "1.4", maxStoreys: 3, buildingLineFrontM: "4", buildingLineSideM: "1.5", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "low", formsRequired: ["splum_form_ekurhuleni", "building_plan_checklist", "motivation_letter"], schemeYear: 2014 },
  { municipality: "ekurhuleni", zoneCode: "RES4", zoneLabel: "Residential 4", maxUnitsPerHa: 110, coveragePct: "70", far: "2.2", maxStoreys: 4, buildingLineFrontM: "3", buildingLineSideM: "1", buildingLineRearM: "2", permittedUses: ["flats", "dwelling_units"], rezoningPossibleTo: [], rezoningDifficulty: "low", formsRequired: ["splum_form_ekurhuleni", "building_plan_checklist", "motivation_letter"], schemeYear: 2014 },
  { municipality: "ekurhuleni", zoneCode: "COM1", zoneLabel: "Business 1", maxUnitsPerHa: 130, coveragePct: "80", far: "2.8", maxStoreys: 5, buildingLineFrontM: "0", buildingLineSideM: "0", buildingLineRearM: "3", permittedUses: ["retail", "offices", "mixed_use"], consentUses: ["flats"], rezoningPossibleTo: ["RES4"], rezoningDifficulty: "medium", formsRequired: ["splum_form_ekurhuleni", "building_plan_checklist", "motivation_letter"], schemeYear: 2014 },
];

async function main() {
  await db.insert(zoningSchemeRules).values(rules).onConflictDoNothing();
  console.log(`Seeded ${rules.length} zoning scheme rules (JHB, Tshwane, Ekurhuleni · RES1-4 + COM1)`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
