"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { actorHeaders } from "@/lib/portal-client";

const steps = ["Confirm current zoning certificate", "Prepare dolomite declaration", "Submit building plan checklist", "Compile pre-application motivation"];
const docs = ["zoning_certificate", "dolomite_declaration", "building_plan_checklist", "motivation_letter"];

export default function ZoningPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState("parcel");
  const [documents, setDocuments] = useState<Array<{ id: number; docType: string; status: string }>>([]);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { params.then(({ id: value }) => { setId(value); fetch(`/api/documents?listingId=${value}`).then((response) => response.ok ? response.json() : []).then(setDocuments); }); }, [params]);
  async function generate() { const response = await fetch("/api/documents", { method: "POST", headers: actorHeaders(), body: JSON.stringify({ listingId: Number(id), municipality: "johannesburg", forms: docs, prefilledData: { erfNumber: `ERF ${id}`, zoneCode: "RES3", municipality: "johannesburg" } }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? "Could not generate documents"); return; } setDocuments(body); setMessage("Compliance documents generated and saved as ready."); }
  return <div className="portal-page"><div className="portal-page-head"><div><p className="eyebrow">Parcel {id} · Compliance</p><h1 className="page-title">Zoning and forms</h1><p className="page-subtitle">RES3 · City of Johannesburg · A working checklist backed by saved compliance documents.</p></div><Link href={`/scout/${id}`} className="button button-quiet">← Back to parcel</Link></div>{message && <div className="card" style={{ padding: "12px 16px", marginBottom: 16, color: "#16653d", background: "#effaf3", borderColor: "#b9e6c9", fontSize: 12, fontWeight: 800 }}>{message}</div>}<div className="grid-2"><section className="card card-pad"><div className="split"><div><span className="card-kicker">Application checklist</span><h2 className="card-title" style={{ marginTop: 6 }}>Keep the file moving</h2></div><span className="tag tag-blue">{documents.filter((document) => document.status === "ready").length} ready</span></div><div className="compliance-timeline">{steps.map((step, index) => { const document = documents[index]; return <div className="compliance-step" key={step}><span className={document?.status === "ready" ? "step-dot complete" : "step-dot"}>{document?.status === "ready" ? "✓" : index + 1}</span><div><strong>{step}</strong><small>{document?.status === "ready" ? "Saved in the compliance workspace" : "Not started"}</small></div><span className={document?.status === "ready" ? "tag tag-green" : "tag"}>{document?.status === "ready" ? "Ready" : "Pending"}</span></div>; })}</div></section><section className="stack"><section className="card card-pad"><span className="card-kicker">Zoning summary</span><h2 className="card-title" style={{ marginTop: 6 }}>Residential 3</h2><div className="list-row"><span><strong>Permitted use</strong><small>Multiple dwelling units</small></span><span className="tag tag-green">Permitted</span></div><div className="list-row"><span><strong>Rezoning</strong><small>Not required for 8 units</small></span><span className="tag tag-blue">Low friction</span></div></section><section className="card card-pad"><span className="card-kicker">Generated documents</span><h2 className="card-title" style={{ marginTop: 6 }}>{documents.length ? `${documents.length} documents saved` : "Compliance package"}</h2><p className="muted" style={{ fontSize: 12, lineHeight: 1.5 }}>Generate a working pack for your planning professional. Status is persisted in the compliance_documents table.</p><button className="button button-primary" style={{ width: "100%", marginTop: 8 }} onClick={generate}>Generate package</button></section></section></div></div>;
}
